-- =====================================================
-- Library Management System - Database Schema
-- Database: library_management
-- Version: 1.0
-- =====================================================

-- Create database
CREATE DATABASE IF NOT EXISTS `library_management` 
  DEFAULT CHARACTER SET utf8mb4 
  DEFAULT COLLATE utf8mb4_general_ci;

USE `library_management`;

-- =====================================================
-- TABLE: users
-- Stores all system users (Admin, Librarian, Student)
-- =====================================================
CREATE TABLE IF NOT EXISTS `users` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `email` VARCHAR(150) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,           -- Stored using password_hash()
    `role` ENUM('Admin', 'Librarian', 'Student') NOT NULL DEFAULT 'Student',
    `phone` VARCHAR(20) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- =====================================================
-- TABLE: categories
-- Book categories/genres
-- =====================================================
CREATE TABLE IF NOT EXISTS `categories` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL UNIQUE,
    `description` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- =====================================================
-- TABLE: books
-- Book catalogue with stock tracking
-- =====================================================
CREATE TABLE IF NOT EXISTS `books` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `author` VARCHAR(150) NOT NULL,
    `isbn` VARCHAR(20) DEFAULT NULL UNIQUE,
    `publisher` VARCHAR(150) DEFAULT NULL,
    `category_id` INT DEFAULT NULL,
    `qty_total` INT NOT NULL DEFAULT 1,          -- Total copies owned
    `qty_available` INT NOT NULL DEFAULT 1,      -- Copies currently available
    `added_by` INT DEFAULT NULL,                 -- User who added this book
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`added_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB;

-- =====================================================
-- TABLE: issued_books
-- Tracks book issue requests, approvals, and returns
-- Status flow: Requested → Issued → Returned
-- =====================================================
CREATE TABLE IF NOT EXISTS `issued_books` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `book_id` INT NOT NULL,
    `user_id` INT NOT NULL,                      -- Student who requested/borrowed
    `issued_by` INT DEFAULT NULL,                -- Librarian who approved
    `issue_date` DATE DEFAULT NULL,              -- Date approved/issued
    `due_date` DATE DEFAULT NULL,                -- Expected return date
    `return_date` DATE DEFAULT NULL,             -- Actual return date
    `status` ENUM('Requested', 'Issued', 'Returned', 'Rejected') NOT NULL DEFAULT 'Requested',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`book_id`) REFERENCES `books`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`issued_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB;

-- =====================================================
-- SEED DATA
-- =====================================================

-- Seed Users
-- Passwords: Admin@123, Librarian@123, Student@123
-- These are bcrypt hashes generated by password_hash()
INSERT INTO `users` (`name`, `email`, `password`, `role`, `phone`) VALUES
('System Admin', 'admin@library.com', '$2y$10$i8UEc4pcOJnvfQK3h2AM3u/QVeVOe.aRcF4/FqdLPmk5QZpmZJQHu', 'Admin', '0771234567'),
('Jane Librarian', 'librarian@library.com', '$2y$10$MItaL9oUjnXdj3cY9eqKduNto6xx2OCxfANlIN6tFOyy6bxq50S8u', 'Librarian', '0779876543'),
('John Student', 'student@library.com', '$2y$10$LcUKEEBm5/SCEsRNMbyyU.W2KXoI5CiA3vfEaMs0m1IrOTqMBizk.', 'Student', '0775551234'),
('Alice Student', 'alice@library.com', '$2y$10$LcUKEEBm5/SCEsRNMbyyU.W2KXoI5CiA3vfEaMs0m1IrOTqMBizk.', 'Student', '0775559999');

-- Seed Categories
INSERT INTO `categories` (`name`, `description`) VALUES
('Computer Science', 'Books on programming, algorithms, data structures, and computer science fundamentals'),
('Mathematics', 'Books covering calculus, algebra, statistics, and applied mathematics'),
('Physics', 'Books on classical mechanics, quantum physics, and thermodynamics'),
('Literature', 'Novels, poetry, drama, and literary criticism'),
('Business', 'Books on management, economics, marketing, and entrepreneurship');

-- Seed Books
INSERT INTO `books` (`title`, `author`, `isbn`, `publisher`, `category_id`, `qty_total`, `qty_available`, `added_by`) VALUES
('Introduction to Algorithms', 'Thomas H. Cormen', '978-0262033848', 'MIT Press', 1, 5, 4, 1),
('Clean Code', 'Robert C. Martin', '978-0132350884', 'Prentice Hall', 1, 3, 3, 1),
('Design Patterns', 'Erich Gamma', '978-0201633610', 'Addison-Wesley', 1, 2, 2, 1),
('Database System Concepts', 'Abraham Silberschatz', '978-0078022159', 'McGraw-Hill', 1, 4, 4, 1),
('Calculus: Early Transcendentals', 'James Stewart', '978-1285741550', 'Cengage Learning', 2, 3, 3, 1),
('Linear Algebra Done Right', 'Sheldon Axler', '978-3319110790', 'Springer', 2, 2, 2, 1),
('University Physics', 'Hugh D. Young', '978-0321696861', 'Pearson', 3, 3, 3, 2),
('To Kill a Mockingbird', 'Harper Lee', '978-0061120084', 'HarperCollins', 4, 4, 4, 2),
('The Great Gatsby', 'F. Scott Fitzgerald', '978-0743273565', 'Scribner', 4, 3, 3, 2),
('The Lean Startup', 'Eric Ries', '978-0307887894', 'Crown Business', 5, 2, 2, 2);

-- Seed Issued Books (sample transactions)
INSERT INTO `issued_books` (`book_id`, `user_id`, `issued_by`, `issue_date`, `due_date`, `return_date`, `status`) VALUES
(1, 3, 2, '2026-02-01', '2026-02-15', NULL, 'Issued'),
(5, 4, 2, '2026-02-05', '2026-02-19', '2026-02-12', 'Returned');

-- Update qty_available for issued book
UPDATE `books` SET `qty_available` = `qty_available` - 1 WHERE `id` = 1;
